// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIMsj7pejKYJCAEOXlOueX_WeY1QlXB6I',
    appId: '1:296968818806:web:200a1039f94e45f43f8f57',
    messagingSenderId: '296968818806',
    projectId: 'trendify-72234',
    authDomain: 'trendify-72234.firebaseapp.com',
    storageBucket: 'trendify-72234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGU2UR5GdNgkN9YkXYRSQW2AIQe1Clbg',
    appId: '1:296968818806:android:1687ad4df36930af3f8f57',
    messagingSenderId: '296968818806',
    projectId: 'trendify-72234',
    storageBucket: 'trendify-72234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9u1M7sk0I4AlGJFaQ8uT1g5ZAWuFZK6E',
    appId: '1:296968818806:ios:51d21d7eba6adc483f8f57',
    messagingSenderId: '296968818806',
    projectId: 'trendify-72234',
    storageBucket: 'trendify-72234.firebasestorage.app',
    iosBundleId: 'com.example.trendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9u1M7sk0I4AlGJFaQ8uT1g5ZAWuFZK6E',
    appId: '1:296968818806:ios:51d21d7eba6adc483f8f57',
    messagingSenderId: '296968818806',
    projectId: 'trendify-72234',
    storageBucket: 'trendify-72234.firebasestorage.app',
    iosBundleId: 'com.example.trendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIMsj7pejKYJCAEOXlOueX_WeY1QlXB6I',
    appId: '1:296968818806:web:bc845ebc58805b483f8f57',
    messagingSenderId: '296968818806',
    projectId: 'trendify-72234',
    authDomain: 'trendify-72234.firebaseapp.com',
    storageBucket: 'trendify-72234.firebasestorage.app',
  );
}
